include ../Make.defines                                     

PROGS=	prog24_01 prog24_02 prog24_03 prog24_04 prog24_05
        

all:	${PROGS}

prog24_01:	prog24_01.o
	${CC} ${CFLAGS} -o $@ prog24_01.o ${LIBS}

prog24_02:	prog24_02.o
	${CC} ${CFLAGS} -o $@ prog24_02.o ${LIBS}

prog24_03:	prog24_03.o
	${CC} ${CFLAGS} -o $@ prog24_03.o ${LIBS}

prog24_04:	prog24_04.o
	${CC} ${CFLAGS} -o $@ prog24_04.o ${LIBS}

prog24_05:	prog24_05.o
	${CC} ${CFLAGS} -o $@ prog24_05.o ${LIBS}
