include ../Make.defines

PROGS:	prog06_01 prog06_02 prog06_03 prog06_04\
        prog06_05 

all:	${PROGS}

prog06_01:	prog06_01.o
		${CC} ${CFLAGS} -o $@ prog06_01.o ${LIBS}

prog06_02:	prog06_02.o
		${CC} ${CFLAGS} -o $@ prog06_02.o ${LIBS}

prog06_03:	prog06_03.o
		${CC} ${CFLAGS} -o $@ prog06_03.o ${LIBS}

prog06_04:	prog06_04.o
		${CC} ${CFLAGS} -o $@ prog06_04.o ${LIBS}

prog06_05:	prog06_05.o
		${CC} ${CFLAGS} -o $@ prog06_05.o ${LIBS}
