include ../Make.defines

PROGS:	prog10_01 prog10_02  prog10_03

all:	${PROGS}

prog10_01:	prog10_01.o
		${CC} ${CFLAGS} -o $@ prog10_01.o ${LIBS}

prog10_02:	prog10_02.o
		${CC} ${CFLAGS} -o $@ prog10_02.o ${LIBS}

prog10_03:	prog10_03.o
		${CC} ${CFLAGS} -o $@ prog10_03.o ${LIBS}
