include ../Make.defines

PROGS=	prog26_01 prog26_02 prog26_03 prog26_04

all:	${PROGS}

prog26_01:	prog26_01.o
	${CC} ${CFLAGS} -o $@ prog26_01.o ${LIBS}

prog26_02:	prog26_02.o
	${CC} ${CFLAGS} -o $@ prog26_02.o ${LIBS}

prog26_03:	prog26_03.o
	${CC} ${CFLAGS} -o $@ prog26_03.o ${LIBS}

prog26_04:	prog26_04.o
	${CC} ${CFLAGS} -o $@ prog26_04.o ${LIBS}
