include ../Make.defines

PROGS=	prog26_01 prog26_02

all:	${PROGS}

prog26_01:	prog26_01.o
	${CC} ${CFLAGS} -o $@ prog26_01.o ${LIBS}

prog26_02:	prog26_02.o
	${CC} ${CFLAGS} -o $@ prog26_02.o ${LIBS}
