include ../Make.defines

PROGS=	prog25_01 prog25_02

all:	${PROGS}

prog25_01:	prog25_01.o
	${CC} ${CFLAGS} -o $@ prog25_01.o ${LIBS}

prog25_02:	prog25_02.o
	${CC} ${CFLAGS} -o $@ prog25_02.o ${LIBS}
