include ../Make.defines

PROGS= prog27_01 prog27_02 prog27_03 envargs

all:	${PROGS}

prog27_01:	prog27_01.o
	${CC} ${CFLAGS} -o $@ prog27_01.o ${LIBS}

envargs:	envargs.o
	${CC} ${CFLAGS} -o $@ envargs.o ${LIBS}

prog27_02:	prog27_02.o
	${CC} ${CFLAGS} -o $@ prog27_02.o ${LIBS}

prog27_03:	prog27_03.o
	${CC} ${CFLAGS} -o $@ prog27_03.o ${LIBS}
