include ../Make.defines

PROGS:	prog08_01 prog08_02 prog08_03 prog08_04

all:	${PROGS}

prog08_01:	prog08_01.o
		${CC} ${CFLAGS} -o $@ prog08_01.o ${LIBS} 

prog08_02:	prog08_02.o
		${CC} ${CFLAGS} -o $@ prog08_02.o ${LIBS}

prog08_03:	prog08_03.o
		${CC} ${CFLAGS} -o $@ prog08_03.o ${LIBS}

prog08_04:	prog08_04.o
		${CC} ${CFLAGS} -o $@ prog08_04.o ${LIBS}	

	

